import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { parseJsoncObject } from "../core/jsonc.js";
import type { Adapter, AdapterCommand, AdapterContext } from "../types.js";

const OPEN_NEXT_CLI = "@opennextjs/cloudflare#../cli/index.js";

function toPosix(value: string): string {
  return value.split(path.sep).join("/");
}

function relativeRoot(context: AdapterContext): string {
  return toPosix(path.relative(context.generatedRoot, context.projectRoot));
}

/**
 * Rewrites repository-relative paths so they still resolve from the generated
 * project, which sits below the repository root.
 *
 * Only string values are considered. An earlier version rewrote every \`"./\`
 * in the file, which also caught comments and any value that merely looked
 * like a path.
 */
function repoint(value: unknown, root: string): unknown {
  if (typeof value === "string") {
    return value.startsWith("./") ? `${root}${value.slice(1)}` : value;
  }

  if (Array.isArray(value)) return value.map((item) => repoint(item, root));

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value as Record<string, unknown>).map(([key, item]) => [
        key,
        repoint(item, root),
      ])
    );
  }

  return value;
}

/**
 * Derives the application's Worker configuration from the repository's own, so
 * compatibility dates, flags and bindings stay in one place and only the name
 * differs.
 *
 * An application that names no Worker gets one derived from the repository's.
 * Every application must end up with a distinct name: without its own
 * configuration, wrangler walks up and resolves the repository's, and deploying
 * would publish over the root application.
 *
 * The file is parsed rather than pattern-matched. \`name\` is a legal key inside
 * bindings too, so matching the first one in the text could rename a binding
 * and leave the Worker sharing the repository's name, which is exactly the
 * collision this exists to prevent. Comments do not survive the round trip;
 * the generated file is build output, and the repository's own copy keeps them.
 */
function wranglerConfig(context: AdapterContext): string | undefined {
  const rootConfig = path.join(context.projectRoot, "wrangler.jsonc");
  if (!existsSync(rootConfig)) return undefined;

  const parsed = parseJsoncObject(
    readFileSync(rootConfig, "utf8"),
    "wrangler.jsonc"
  );

  const rootName = typeof parsed.name === "string" ? parsed.name : undefined;
  const configured = context.appOptions.deploy?.name;

  const name =
    typeof configured === "string" && configured
      ? configured
      : rootName
        ? `${rootName}-${context.appName}`
        : context.appName;

  const config = repoint(parsed, relativeRoot(context)) as Record<
    string,
    unknown
  >;
  config.name = name;

  return `${JSON.stringify(config, null, 2)}\n`;
}

export interface CloudflareAdapterOptions {
  /**
   * Path to the repository's OpenNext configuration, relative to the
   * repository root. Defaults to `open-next.config.ts`.
   */
  openNextConfig?: string;
}

export default function cloudflare(
  options: CloudflareAdapterOptions = {}
): Adapter {
  const openNextConfig = options.openNextConfig ?? "open-next.config.ts";

  return {
    name: "cloudflare",

    nextConfig: {
      module: "next-multi-app/cloudflare/next-config",
      importName: "withCloudflare",
    },

    files(context) {
      const files: Record<string, string> = {};
      const root = relativeRoot(context);
      const withoutExtension = openNextConfig.replace(/\.[cm]?[jt]s$/, "");

      if (existsSync(path.join(context.projectRoot, openNextConfig))) {
        files["open-next.config.ts"] =
          "// Generated by next-multi-app. Edit multi-app.config.mjs, not this file.\n" +
          `export { default } from ${JSON.stringify(`${root}/${withoutExtension}`)};\n`;
      }

      const wrangler = wranglerConfig(context);
      if (wrangler) files["wrangler.jsonc"] = wrangler;

      return files;
    },

    actions(): Record<string, AdapterCommand[]> {
      return {
        deploy: [
          { bin: OPEN_NEXT_CLI, args: ["build"] },
          { bin: OPEN_NEXT_CLI, args: ["deploy"] },
        ],
        preview: [
          { bin: OPEN_NEXT_CLI, args: ["build"] },
          { bin: OPEN_NEXT_CLI, args: ["preview"] },
        ],
        upload: [
          { bin: OPEN_NEXT_CLI, args: ["build"] },
          { bin: OPEN_NEXT_CLI, args: ["upload"] },
        ],
        "cf-typegen": [
          {
            bin: "wrangler",
            args: [
              "types",
              "--env-interface",
              "CloudflareEnv",
              "cloudflare-env.d.ts",
            ],
          },
        ],
      };
    },
  };
}
