import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import path from "node:path";
import type { AdapterContext, ResolvedConfig } from "../types.js";
import {
  detectLinkMode,
  materialiseDirectoryLink,
  materialiseFile,
  type LinkMode,
} from "./link.js";
import { applyPlan, planOverlay } from "./overlay.js";
import { isInside } from "./paths.js";

export interface MaterialiseResult {
  /** Absolute path to the generated Next.js project. */
  generatedRoot: string;
  /** True when the shape of the route tree changed. */
  changed: boolean;
  mode: LinkMode;
}

const GENERATED_HEADER =
  "// Generated by next-multi-app. Edit multi-app.config.mjs, not this file.";

function writeIfChanged(file: string, contents: string): void {
  if (existsSync(file) && readFileSync(file, "utf8") === contents) return;
  writeFileSync(file, contents);
}

function toPosix(value: string): string {
  return value.split(path.sep).join("/");
}

function nextConfigSource(
  config: ResolvedConfig,
  relativeProjectRoot: string,
  noindex: boolean
): string {
  const adapter = config.adapter?.nextConfig;

  const imports = [`import { createAppConfig } from "next-multi-app/config";`];
  if (adapter) {
    imports.push(
      `import { ${adapter.importName} } from ${JSON.stringify(adapter.module)};`
    );
  }

  const call = [
    `createAppConfig({`,
    `  root: __dirname,`,
    `  projectRoot: ${JSON.stringify(relativeProjectRoot)},`,
    `  noindex: ${noindex},`,
    `})`,
  ].join("\n");

  const body = adapter ? `${adapter.importName}(\n${indent(call)}\n)` : call;

  return `${GENERATED_HEADER}\n${imports.join("\n")}\n\nexport default ${body};\n`;
}

function indent(value: string): string {
  return value
    .split("\n")
    .map((line) => (line ? `  ${line}` : line))
    .join("\n");
}

function tsconfigSource(relativeTsconfig: string): string {
  return `${JSON.stringify(
    {
      extends: relativeTsconfig,
      compilerOptions: { paths: { "@/*": ["./*"] } },
      // `include` and `exclude` are deliberately restated. TypeScript resolves
      // an inherited `include` relative to the file that declared it, so
      // omitting them here would pull the repository's own sources into this
      // project's type check.
      include: [
        "next-env.d.ts",
        "**/*.ts",
        "**/*.tsx",
        ".next/types/**/*.ts",
        ".next/dev/types/**/*.ts",
      ],
      exclude: ["node_modules"],
    },
    null,
    2
  )}\n`;
}

/**
 * Links the repository's environment files into a generated project.
 *
 * Next loads `.env*` relative to the directory it is building, which is the
 * generated project rather than the repository. Without these an application
 * silently runs with no environment at all, and every request to a configured
 * service fails at the first URL it tries to build.
 *
 * Links are always used, even under copy mode, so an edited value takes effect
 * without re-running anything. A link left pointing at a deleted file stops the
 * build outright, so stale ones are pruned first.
 */
function linkEnvFiles(projectRoot: string, generatedRoot: string): void {
  const wanted = new Set(
    readdirSync(projectRoot).filter((name) => name.startsWith(".env"))
  );

  for (const name of readdirSync(generatedRoot)) {
    if (!name.startsWith(".env") || wanted.has(name)) continue;
    rmSync(path.join(generatedRoot, name), { recursive: true, force: true });
  }

  for (const name of wanted) {
    materialiseFile(
      path.join(generatedRoot, name),
      path.join(projectRoot, name),
      "symlink"
    );
  }
}

/**
 * Builds the real Next.js project for one application and returns its root.
 *
 * Next.js resolves both its configuration and its route tree from a single
 * directory, and only ever looks for routes in `app/` or `src/app/`. Nothing
 * separates the two, so an application directory cannot itself be a Next
 * project. This assembles one whose `app/` is the merged view of the shared
 * route files and the application's own.
 */
export function materialise(
  appName: string,
  config: ResolvedConfig,
  projectRoot: string
): MaterialiseResult {
  const appOptions = config.apps[appName];
  if (!appOptions) {
    throw new Error(`Unknown application ${JSON.stringify(appName)}.`);
  }

  const appsDir = path.resolve(projectRoot, config.appsDir);
  const appDir = path.join(appsDir, appName);

  if (!existsSync(appDir)) {
    throw new Error(
      `${toPosix(path.relative(projectRoot, appDir))} does not exist. ` +
        "Create it before building this application."
    );
  }

  const outDir = path.resolve(projectRoot, config.outDir);
  const generatedRoot = path.join(outDir, appName);
  mkdirSync(generatedRoot, { recursive: true });

  // The generated tree is build output. Ignoring it from inside means a
  // consumer never has to remember to add it to their own ignore file.
  writeIfChanged(path.join(outDir, ".gitignore"), "*\n");

  const mode = detectLinkMode(outDir);

  // Shared route content is everything at the top of the applications
  // directory that is not itself an application. The exclusion applies only to
  // that level, so an application may still own a route segment whose name
  // matches another application.
  const plan = planOverlay(
    [appsDir, appDir],
    [new Set(Object.keys(config.apps))]
  );

  const changed = applyPlan(path.join(generatedRoot, "app"), plan, mode);

  for (const name of config.sharedDirs) {
    const target = path.resolve(projectRoot, name);
    if (!existsSync(target)) continue;
    materialiseDirectoryLink(path.join(generatedRoot, name), target, mode);
  }

  linkEnvFiles(projectRoot, generatedRoot);

  const relativeProjectRoot = toPosix(
    path.relative(generatedRoot, projectRoot)
  );

  writeIfChanged(
    path.join(generatedRoot, "next.config.ts"),
    nextConfigSource(config, relativeProjectRoot, Boolean(appOptions.noindex))
  );

  const rootTsconfig = path.join(projectRoot, "tsconfig.json");
  if (existsSync(rootTsconfig)) {
    writeIfChanged(
      path.join(generatedRoot, "tsconfig.json"),
      tsconfigSource(`${relativeProjectRoot}/tsconfig.json`)
    );
  }

  const context: AdapterContext = {
    projectRoot,
    appName,
    appOptions,
    generatedRoot,
  };

  for (const [file, contents] of Object.entries(
    config.adapter?.files?.(context) ?? {}
  )) {
    const destination = path.join(generatedRoot, file);

    // An adapter is code the repository chose to import, so this is not a
    // trust boundary. It is a guard against a path built by hand from an
    // application name or an option, which would otherwise write anywhere.
    if (!isInside(generatedRoot, destination)) {
      throw new Error(
        `Adapter ${config.adapter?.name ?? "unknown"} tried to write ` +
          `${JSON.stringify(file)}, which is outside the generated project.`
      );
    }

    mkdirSync(path.dirname(destination), { recursive: true });
    writeIfChanged(destination, contents);
  }

  return { generatedRoot, changed, mode };
}
